Update translation strings for energy validator
home-assistant/frontend pull request #10037
Opened 2021-09-15 10:49 UTC by emontnemery

## Proposed change

Update translation strings for energy validator
Note: Depends on core PR #TODO

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-09-15 10:54 UTC, bramkragten commented on src/translations/en.json
> +                "description": "The following entity has state class measurement but last reset is missing"
```suggestion
                "description": "The following entity has state class 'measurement' but 'last_reset' is missing"
```

2021-09-16 19:24 UTC, spacegaier requested changes

2021-09-16 19:24 UTC, spacegaier commented on src/translations/en.json
> +                "description": "The following entities have state class 'measurement' but 'last_reset' is missing"
```suggestion
                "description": "The following entities have state class 'measurement' but 'last_reset' is missing:"
```

2021-09-20 10:38 UTC, bramkragten approved these changes

2021-09-20 10:38 UTC, merged