List lights in group in the group's more-info dialog
home-assistant/frontend pull request #10619
Opened 2021-11-14 05:37 UTC by Klikini

## Proposed change

The more info dialog for light groups used to show a list of the lights in the group, but this was removed with the launch of Lovelace (#9967). I would like to add them back, as shown in the screenshot of this change below:

![image](https://user-images.githubusercontent.com/1693960/141669026-65281799-1bc0-4874-8003-50974c2d4c27.png)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

No config changes.

## Additional information

- This PR fixes or closes issue: fixes #9967
- This PR is related to issue or discussion: N/A
- Link to documentation pull request: N/A

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-11-15 22:08 UTC, spacegaier requested changes

2021-11-15 22:08 UTC, spacegaier commented on src/dialogs/more-info/controls/more-info-light.ts
> +    const memberLightsHeader = "Lights in this group";
This needs to be made translatable

2021-11-22 10:08 UTC, bramkragten commented
The old behaviour was for a `group` (https://www.home-assistant.io/integrations/group/) not for a `light.group` (https://www.home-assistant.io/integrations/light.group/)

We do not allow UI for specific integrations, just for standardized attributes of the domain.

2021-11-24 06:30 UTC, Klikini commented
@bramkragten I get where you're coming from, but this isn't for a specific "integration" per se. I understand light groups are considered an "integration", but they are also a basic/generic function of Home Assistant (as opposed to something specific like Hue or LIFX) and I don't think it's unreasonable to provide a nicer interface for them.

That said, would it be more acceptable to implement this in the more info dialogs for *all* types of groups? Viewing the entities that are in a group seems like a common task that happens in every piece of software I've used, to the point where I feel it should've been included in the first release with Lovelace, and I was very surprised this wasn't the case.

2021-11-29 09:12 UTC, bramkragten commented
I think we should add a UI to create and manage groups, when we have that, we could consider linking to that from the more-info dialog.

2022-01-24 16:44 UTC, zsarnett commented
Closing. Once we have group manager UI we can revisit but it will probably require a rewrite

2022-01-24 16:44 UTC, closed without merging