Improve ha-panel-dev-serivce.html
home-assistant/frontend pull request #130
Opened 2016-10-17 13:48 UTC by justweb1

Move available services list to dropdown menu.

**TODO**
[ ] Fix width of dropdown

2016-10-18 13:14 UTC, justweb1 commented
Tested in production and is working.

2016-10-19 01:43 UTC, balloob requested changes

2016-10-19 01:43 UTC, balloob commented on bower.json
> +    "neon-animation": "PolymerElements/neon-animation#^1.2.4"
You're not using this.

2016-10-19 01:43 UTC, balloob commented on bower.json
> +    "app-storage": "PolymerElements/app-storage#^0.9.7",
Please add it to devDependencies

2016-10-19 01:43 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> -<link rel="import" href="../../bower_components/polymer/polymer.html">
It's very annoying that you decided to change the quote style because it makes it very difficult to see what imports have changed

2016-10-19 01:43 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> +      <app-localstorage-document
Why did you add all the other app-localstorage-document elements as children of this one?

2016-10-19 01:43 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> +            <paper-dropdown-menu class='dropdown-menu' label='Available Services' focused>
Why should this be focused. I would expect the input text field to keep focus.

2016-10-19 01:43 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> -          <services-list on-service-selected='serviceSelected' hass='[[hass]]'></services-list>
I think it's better to keep the services inside `services-list` component so it keeps this component manegable. There is no reason both should be merged.

2016-10-19 01:43 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> +    console.log(ev);
stale logging

2016-10-19 02:15 UTC, justweb1 commented on panels/dev-service/ha-panel-dev-service.html
> -<link rel="import" href="../../bower_components/polymer/polymer.html">
Sorry about that. I didn't think about it. I was just trying to clean it up. Next time I will do that in a seperate commit.

2016-10-19 02:16 UTC, justweb1 commented on panels/dev-service/ha-panel-dev-service.html
> +      <app-localstorage-document
Fixed.

2016-10-19 02:21 UTC, justweb1 commented
Instead of dropdown I switched to combo boxes. They allow filtering and still have a drop down component. I also broke out domains and services to make it even easier and cleaner.

2016-10-19 02:28 UTC, justweb1 commented on bower.json
> +    "app-storage": "PolymerElements/app-storage#^0.9.7",
Fixed

2016-10-19 02:30 UTC, justweb1 commented on panels/dev-service/ha-panel-dev-service.html
> +            <paper-dropdown-menu class='dropdown-menu' label='Available Services' focused>
Removed.

2016-10-19 06:28 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
>        <div class$='[[computeFormClasses(narrow)]]'>
This is no longer necessary

2016-10-19 06:29 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
>        <div class$='[[computeFormClasses(narrow)]]'>
Means we also no longer have to include the custom style `iron-flex` and `iron-positioning`

2016-10-19 06:31 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
>        <div class$='[[computeFormClasses(narrow)]]'>
The method computeFormClasses can also be removed. Instead just have `content`. I am not 100% sure why we needed `fit` anymore. Make sure the background remains all white. If that's not the case you should add `fit` back and also `iron-positioning`.

2016-10-19 14:21 UTC, justweb1 commented on panels/dev-service/ha-panel-dev-service.html
>          <div class='flex'>
Done.

2016-10-19 14:24 UTC, justweb1 commented
Just need to fix the width of the dropdown overlay, I can set the max-width but I am having trouble positioning it to the right. If It can't be positioned to the right I don't think it is worth setting a max width on it.

2016-10-20 01:27 UTC, justweb1 commented
@balloob I can not figure out the max-width for the vaadin-combo-box-overlay. I tried multiple different ways that I knew and also that I researched. This does not break functionality and it looks like there will be an better way to do this in native shadow dom after the polymer 2.0 upgrade. It is definitely possible that I missed something but I've been racking my brain on this one.

2016-10-21 05:20 UTC, balloob commented
Shadow DOM should not render any differently. It looks like the combo box goes max width by default so just wrap it in a div that has a max-width set via CSS.

2016-10-22 01:11 UTC, justweb1 commented
@balloob take a look. should be ready to merge. I though initially you only wanted the drop down itself with a max-width not the whole form. That is why I was trying to penetrate the child dom.

2016-10-22 03:39 UTC, balloob approved these changes

2016-10-22 03:40 UTC, merged