Add dependabot
home-assistant/frontend pull request #13073
Opened 2022-07-04 18:00 UTC by wrt54g

## Breaking change

## Proposed change

I added dependabot config for actions.
## Type of change

- [X] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2022-07-04 18:01 UTC, frenck requested changes

2022-07-04 18:01 UTC, frenck commented on .github/dependabot.yml
> +      interval: daily
Is enough.

```suggestion
      interval: weekly
```

2022-07-05 04:21 UTC, wrt54g commented
@frenck It's fixed.

2022-07-05 07:40 UTC, frenck approved these changes
Thanks, @wrt54g 👍

2022-07-05 07:40 UTC, merged