Lovelace: entity-filter: hide card when entities[] empty
home-assistant/frontend pull request #1373
Opened 2018-06-30 07:58 UTC by ciotlosm

Implements https://github.com/home-assistant/ui-schema/issues/48

- [ ] developer documentation

Sample:
```yaml
title: Lovelace Demo
views:
  - title: Home
    icon: mdi:heart
    cards:
      - type: entity-filter
        hide_if_empty: false
        filter:
          - domain: lig2ht
        card:
          title: domain light
```

2018-06-30 12:49 UTC, c727 commented
maybe we should add this logic to `entities` and `glance` instead, something like `hide if no device in the list is online`?

2018-06-30 14:38 UTC, balloob commented
I think filter is the right place. A user is explicit in what entities to show for the others, if they don't want to see the card they can remove it

2018-06-30 14:39 UTC, balloob approved these changes

2018-06-30 14:39 UTC, balloob commented on src/panels/lovelace/cards/hui-entity-filter-card.js
> +    this._computeVisibility(entitiesList.length);
I don't really see a reason to extract this into a method

2018-06-30 17:16 UTC, c727 commented
ok, should we make it optional? `hide_if_empty`

2018-06-30 17:56 UTC, ciotlosm commented
>ok, should we make it optional? `hide_if_empty`

@c727 it is optional. By default is false

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-07-01 02:53 UTC, balloob commented on src/panels/lovelace/cards/hui-entity-filter-card.js
> +    if (this._config.hide_if_empty) {
This is incorrect. This means that if I change the config, and set hide_if_empty to false, it might never show itself again.

2018-07-01 02:54 UTC, balloob commented on src/panels/lovelace/cards/hui-entity-filter-card.js
> +    if (this._config.hide_if_empty) {
I'm also not a big fan of negative config options that then have to be set to true.

I prefer: `show_empty: true/false` with default `true`.

2018-07-01 02:54 UTC, balloob requested changes
We should make sure that changing config resets all things on the element.

2018-07-01 16:48 UTC, balloob approved these changes

2018-07-01 16:55 UTC, merged