Avoid tabbing onto show/hide password icon.
home-assistant/frontend pull request #13954
Opened 2022-10-02 19:35 UTC by karliemeads

## Breaking change

Users exclusively navigating the webgui using a keyboard may not be able to button for showing/hiding password fields.

I suggest that the impact of this would be low, as displaying passwords should be discouraged.

## Proposed change

When filling out a form, such as the initial onboarding/creation of a new user the password field is used. This password field currently has two "tab-selectable" items: the password input box, and the icon/button to toggle showing or hiding of the password.

Intuitively, when I am filling out the onboarding form, I will click on the "Name field", tab to the username field, and so-on through the password and confirm password field, finally using enter to submit.

However, when attempting to tab between the password and confirm password field, tabbing currently selects the icon first, confusing the user and causing them to press the tab button a second time to get to their actual desired field.

<img width="200" alt="Screen Shot 2022-10-02 at 3 25 56 PM" src="https://user-images.githubusercontent.com/68717336/193472550-6e4772dc-e941-40a8-ae01-dbff7b12ce3a.png"> **VS** <img width="206" alt="Screen Shot 2022-10-02 at 3 26 57 PM" src="https://user-images.githubusercontent.com/68717336/193472553-b043ee37-76fe-4a32-9b28-643acefc5a4e.png">

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

Reset Home Assistant to a default configuration, to trigger the onboarding process. Fill out the create user form, primarily using the keyboard to tab between fields.

## Additional information

While there is not a forum post, I believe this should be tagged as WTH.

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

2022-10-02 21:41 UTC, steverep requested changes
These buttons previously had `tabindex="-1"` and I purposely removed it for accessibility.  They should be in the tab sequence unless there is some other redundant method, which is not the case here.  If the functionality exists, it must be keyboard operable.

2022-10-02 22:03 UTC, karliemeads commented
> These buttons previously had `tabindex="-1"` and I purposely removed it for accessibility. They should be in the tab sequence unless there is some other redundant method, which is not the case here. If the functionality exists, it must be keyboard operable.

I've reverted this to draft for some time to think/research about how best to approach this. I agree that keyboard functionality is important to keep. However, I don't think keyboard functionality should negatively impact other user's experience (which is the case currently).

I'm considering alternative methods of tab order, where the button toggles would come after the create or submit option. However, this just puts the intuitive behaviour as negatively affecting accessibility users instead of regular users.

I'd also like to evaluate arrow key functionality as an option, where the keyboard user would tab into the password field, and then use the right arrow to "scroll" to the end of the field, and then press the right arrow once more to select the button toggle. However, I'll need to spend some time determining how this would need to be coded, hence the revert to draft PR.

Thanks for the clear feedback!

2022-10-02 22:28 UTC, steverep commented
Keep in mind:
1. Also for a11y, visual order must match the DOM order, so changing the tab sequence without moving the buttons is not acceptable.
2. Overriding keyboard controls inside a text field must be done very carefully and is generally not a good idea.  For example, your suggestion of using arrow keys would prevent me from navigating or selecting the characters.

I use screen readers all the time and I only really see either no show/hide functionality or a button/checkbox after the field.  For forms with multiple password fields, occasionally one button will control them all.

2022-10-02 22:36 UTC, karliemeads commented
> Keep in mind:
> 
> 1. Also for a11y, visual order must match the DOM order, so changing the tab sequence without moving the buttons is not acceptable.
> 2. Overriding keyboard controls inside a text field must be done very carefully and is generally not a good idea.  For example, your suggestion of using arrow keys would prevent me from navigating or selecting the characters.
> 
> I use screen readers all the time and I only really see either no show/hide functionality or a button/checkbox after the field. For forms with multiple password fields, occasionally one button will control them all.

I'll look into a11y specifically. In my research I've only came across webiam so far.

1. In terms of accessiblity, is it permissible treat the show/hide functionality of the specific password field as a "child" of the tab selection of the password field. You wouldn't be able to tab to it directly, but you would use the arrow keys to select it as I describe in 2.

2. I agree with this. See http://jsfiddle.net/88VL8/7/ (created by someone else) for what I had envisioned in my head. The selection of the show/hide button would only happen when you are at the last character inputted into the text box and press the right arrow.

3? This is what I saw when I checked to see what google was doing for their create user accounts.

2022-10-03 02:48 UTC, steverep commented
I don't see how the "child" approach you are describing could possibly be made accessible without really over-complicating the user experience.

Google's create user and login pages appear to me to just have a checkbox after the password fields that is in the tab sequence.

2022-10-03 22:06 UTC, karliemeads commented
> I don't see how the "child" approach you are describing could possibly be made accessible without really over-complicating the user experience.
> 
> Google's create user and login pages appear to me to just have a checkbox after the password fields that is in the tab sequence.

I spent some tiime today going through a couple of different login forms. A large portion of them did not inclue a "show password" functionality at all. I think some thought should be put into whether we even want to include a toggle for this functionality.

@matthiasdebaat I've tagged you for your input on the UX of whether this button should even exist. There's likely some security considerations that should be thought about.

--------

@steverep In regards to my proposal I have created a diagram.

<img width="449" alt="Screen Shot 2022-10-03 at 5 36 49 PM" src="https://user-images.githubusercontent.com/68717336/193694321-a0e734cb-cfff-4543-b6f1-5e2a597e7b7e.png">

The sections outlined in orange/blue represent tab selectable areas, which the text input or create account button being where the cursor goes. The yellow arrows repesent the use of tab in the forward direction. This to me is clearly intuitive, and likely the desired functionality of non-accessible users

However, as you fairly stated, we should/must also consider keyboard & accessible users. 


The sub-sections outlined in purple/pink represent "columns" within the tab selectable area. These would be internally navigable using the arrow left and right keys, as demonstrated by the green arrows, with the password input text being the default selection.

We may consider using some css or other methods to clearly show what "tab section" is selected.

If we cannot do the above, we should either stick with the status quo, remove the show/hide toggle password feature, or move the show/hide toggle as a seperate checkbox that would have a tab index after create account.

2022-10-04 08:27 UTC, matthiasdebaat commented
> @matthiasdebaat I've tagged you for your input on the UX of whether this button should even exist. There's likely some security considerations that should be thought about.

The `show`/`hide` password button helps users who have troubles to login. Unfortunately we don't have a forgot password feature, so from usability reasons we need to keep this.

About the tabbing. I agree with @steverep to keep it in order as it is shown on the screen. It's a big help for users with screen readers and small annoyance for people wo don't use it. When focused the circle of the `mwc-icon-button` is a bit small. I think we can make the tabbing clearer by making the circle bigger, for example 32px instead of the current 24px. Can we do that without making the icon bigger?

<img width="395" alt="CleanShot 2022-10-04 at 10 19 59@2x" src="https://user-images.githubusercontent.com/20203284/193770186-6a3e3765-923e-4e57-aeba-ed5330ce16c2.png">

2022-10-04 10:31 UTC, karliemeads commented
> > @matthiasdebaat I've tagged you for your input on the UX of whether this button should even exist. There's likely some security considerations that should be thought about.
> 
> The `show`/`hide` password button helps users who have troubles to login. Unfortunately we don't have a forgot password feature, so from usability reasons we need to keep this.
> 
> About the tabbing. I agree with @steverep to keep it in order as it is shown on the screen. It's a big help for users with screen readers and small annoyance for people wo don't use it. When focused the circle of the `mwc-icon-button` is a bit small. I think we can make the tabbing clearer by making the circle bigger, for example 32px instead of the current 24px. Can we do that without making the icon bigger?
> 
> <img alt="CleanShot 2022-10-04 at 10 19 59@2x" width="395" src="https://user-images.githubusercontent.com/20203284/193770186-6a3e3765-923e-4e57-aeba-ed5330ce16c2.png">

I intend to look into increasing the visibility of the focus on this button. perhaps even changing the color may be an option. However, I think changing the focus is a large enough change from the original intent of this PR, that it should be submitted as new, hopefully providing a clear historical view of the code base.

2022-10-04 10:31 UTC, closed without merging

2022-10-04 13:06 UTC, steverep commented
@karliemeads I am legally blind so the graphics don't add much to the explanation for me.  If you have a live example in a code pen or submit a new PR, I'd be happy to review.

I would also encourage you not to try to distinguish "accessible" vs. "non-accessible" users in your design.  People with disabilities encompass the full spectrum with both overlapping and separate needs.  WebAIM is a good resource, but I would suggest starting with [W3C's WAI site](https://www.w3.org/WAI/).

2022-10-04 23:01 UTC, karliemeads commented
@steverep I do not have a live example for you to review. Ihad intended to use example 2 from the Layout Grids https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html mashed together with a text box. The idea being that the grid would be a table with 1 row and 2 columns, the first cell being the text input box for the password, and the user can "arrow right" to the show/hide password toggle. This would then be repeated again in the "confirm password" field.

However, I spent some time researching some different websites. I came across 3 common situations:
- No show/hide password toggle
- The show/hide password toggle was not keyboard navigable
- The show/hide password toggle was immediately selected next in the tab sequence after the password input field.

Based on this, I don't think Home-Assistant should be introducing different functionality (such as what I was suggesting with arrow key navigation). I think keeping it simple is likely the best path forward, excluding a dream one day in the future where we don't need to have passwords at all :) .

---------------------------

> I would also encourage you not to try to distinguish "accessible" vs. "non-accessible" users in your design. People with disabilities encompass the full spectrum with both overlapping and separate needs. WebAIM is a good resource, but I would suggest starting with [W3C's WAI site](https://www.w3.org/WAI/).

This is a great reminder. Thank you for spending the time providing me with great resources and constructive feedback :) .