Fix language detection for country codes
home-assistant/frontend pull request #1426
Opened 2018-07-08 18:32 UTC by c727

navigator.languages = ["de-DE"],  navigator.languages = "de-DE" was detected as en before

2018-07-08 18:45 UTC, quthla commented
Looks good but I still think we should loop through all navigator.languages first, look for full match. If no match found, loop again but split string like with navigator.language and look for match. As a last resort if still no match, fallback to navigator.language.

I think that would be best for all and not break anything, or?

2018-07-08 18:56 UTC, quthla requested changes

2018-07-08 18:56 UTC, quthla commented on src/util/hass-translation.js
>      for (let i = 0; i < navigator.languages.length; i++) {
for of or forEach

2018-07-08 19:06 UTC, c727 commented
if we split the values in languages[] we will get (worst case scenario) false results for chinese languages

2018-07-08 19:10 UTC, quthla commented
That's why I suggested 2 seperate loops. First full match, then another loop after for partial match. Not in the same loop.

2018-07-08 19:19 UTC, c727 commented
I don't think that's necessary. Usually browsers have it already correct in their list like `[en-XX, en-US, en]`

2018-07-08 20:03 UTC, quthla requested changes

2018-07-08 20:03 UTC, quthla commented on src/util/hass-translation.js
>          return translation;
You'd better use for of as else the return will only return from the arrow function

2018-07-09 08:25 UTC, balloob approved these changes

2018-07-09 12:43 UTC, merged