Add frontend support for `datetime` platform
home-assistant/frontend pull request #14391
Opened 2022-11-16 04:24 UTC by raman325

## Proposed change
Adds support for the `date` platform outlined in https://github.com/home-assistant/architecture/discussions/811

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- Link to core pull request: https://github.com/home-assistant/core/pull/81943
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2023-02-17 14:51 UTC, raman325 commented
not stale

2023-05-24 09:54 UTC, bramkragten approved these changes

2023-05-25 10:15 UTC, bramkragten requested changes

2023-05-25 10:15 UTC, bramkragten commented on src/panels/lovelace/entity-rows/hui-datetime-entity-row.ts
> +          .value=${stateObj.state.split(" ")[0]}
I found out that unlike `input-datetime`, the `datetime` state is actually timezone aware, we should handle that.

2023-05-25 15:21 UTC, bramkragten approved these changes

2023-05-29 21:32 UTC, merged