Add support for previews in data flows
home-assistant/frontend pull request #17533
Opened 2023-08-09 12:33 UTC by bramkragten

## Proposed change

Adds support for live previews when working with a data flow (config, options, repair, etc)

![CleanShot 2023-08-09 at 14 32 59](https://github.com/home-assistant/frontend/assets/5662298/b883507d-3c92-4395-bdb4-6ae18ffa5867)

https://github.com/home-assistant/frontend/assets/5662298/0a76ea81-79e3-4d8d-b7be-5e7301a7b1a6

For: https://github.com/home-assistant/core/pull/83638

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2023-08-10 07:59 UTC, emontnemery requested changes, later dismissed

2023-08-10 07:59 UTC, emontnemery commented on src/dialogs/config-flow/previews/flow-preview-sensor_group_preview.ts
This should be renamed to `src/dialogs/config-flow/previews/flow-preview-group_sensor.ts`

2023-08-10 10:48 UTC, piitaya submitted a review, later dismissed
Front-end code LGTM. 
I think we can improve the UX in a future PR.

2023-08-22 08:11 UTC, piitaya approved these changes

2023-08-22 08:30 UTC, merged