Update url on tab reorder
home-assistant/frontend pull request #18169
Opened 2023-10-09 21:02 UTC by pierosavi

## Proposed change

This is a fix for a bug I found when modifying the order of tabs in the home page.
There's no issue connected, let me know if I should open it.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

Tabs without a set path get their path by the position index, when changing the position it's impossible to navigate to the tab with the "old" index as the url doesn't update.
I added a forced update when a tab without a path gets moved.

## Additional information

Old behavior: 

![Kapture 2023-10-09 at 22 54 26](https://github.com/home-assistant/frontend/assets/15440183/e6b52713-8d18-4a59-8f85-e12abccd51f5)

New:

![Kapture 2023-10-09 at 22 55 42](https://github.com/home-assistant/frontend/assets/15440183/2c3e872e-c6de-48f9-b874-8ae1ab06f0f8)

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2023-10-10 10:56 UTC, bramkragten commented on src/panels/lovelace/hui-root.ts
> +      this._navigateToView(newIndex);
```suggestion
      this._navigateToView(newIndex, true);
```

2023-10-10 10:57 UTC, bramkragten requested changes
Great thanks! 🎉 

We should replace the url in the history stack, as it is the same page with a new url.

2023-10-10 20:54 UTC, pierosavi commented
Thanks @bramkragten :)

2023-10-11 10:49 UTC, bramkragten approved these changes

2023-10-11 10:49 UTC, merged