Update link to devs_ux channel on discord
home-assistant/frontend pull request #18569
Opened 2023-11-08 14:38 UTC by MatzeG1t

the old link was an invitation, this link was created just now from the discord app (non invitation)

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2023-11-09 02:19 UTC, KTibow commented
the link you sent is a link to a message that only works if the user is already in there. instead consider linking to https://www.home-assistant.io/join-chat/

2023-11-09 07:58 UTC, frenck commented on gallery/src/pages/concepts/home.markdown
> +- Meet us at <a href="https://discord.com/channels/330944238910963714/867715211619074048" rel="noopener noreferrer" target="_blank">devs_ux Discord</a>. Feel free to share your designs, user test or
```suggestion
- Meet us at <a href="https://www.home-assistant.io/join-chat" rel="noopener noreferrer" target="_blank">devs_ux Discord</a>. Feel free to share your designs, user test or strategic ideas.
```

2023-11-09 16:51 UTC, frenck requested changes
Thanks for the PR @MatzeG1t 👍 

Please note, you need to sign our CLA (as the bot above mentioned) before we can merge this. Can you take a look?

../Frenck

2023-11-28 12:22 UTC, bramkragten approved these changes

2023-11-28 12:24 UTC, bramkragten commented
Stale, updated the link

2023-11-28 12:24 UTC, closed without merging