Add multi select to automations
home-assistant/frontend pull request #20291
Opened 2024-03-30 16:31 UTC by bramkragten

## Proposed change

Adds multi select to the automation config panel, allows to bulk:
- change category
- add label
- enable
- disable

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-03-30 21:07 UTC, piitaya requested changes
I moved `md-menu` outside the scrollable container because of the iOS overflow issue. It's not possible to have an overflow-y: visible inside with an overflow-x: visible. 

This would reintroduced these bugs : https://github.com/home-assistant/frontend/issues/20222 and https://github.com/home-assistant/frontend/issues/20224. I tested the PR on my iPhone and the menu is broken again 😢

2024-03-30 21:14 UTC, piitaya commented
Do we need the "close selection mode" as we already have the close icon on the top right?

![IMG_3480](https://github.com/home-assistant/frontend/assets/5878303/ba7b6e2a-9704-4952-b292-3505a8a61100)

I also noticed dark mode issue with text color and icon color.

![IMG_3482](https://github.com/home-assistant/frontend/assets/5878303/4b974e04-879e-479e-b5d2-69bfc0fcda31)

2024-03-30 23:25 UTC, bramkragten commented
> Do we need the "close selection mode" as we already have the close icon on the top right?

🤷‍♂️ ask design

2024-04-02 08:14 UTC, piitaya approved these changes

2024-04-02 08:14 UTC, merged