Put rename entities in expandable when renaming device
home-assistant/frontend pull request #22182
Opened 2024-10-01 19:44 UTC by bramkragten

## Proposed change

![image](https://github.com/user-attachments/assets/b329212e-41e5-4385-9c66-23b2995e0f94)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-10-01 19:54 UTC, piitaya requested changes

2024-10-01 19:54 UTC, piitaya commented on src/panels/config/devices/ha-config-device-page.ts
> +                    { deviceSlug: oldDeviceSlug }
`count` should be passed here.

2024-10-02 06:28 UTC, silamon commented on src/panels/config/devices/ha-config-device-page.ts
> +import "../../../components/ha-md-list-item";
```suggestion
```

2024-10-02 07:14 UTC, piitaya approved these changes

2024-10-02 07:19 UTC, merged