Show local network URL used in Home Assistant URL settings
home-assistant/frontend pull request #22379
Opened 2024-10-15 09:45 UTC by MindFreeze

## Proposed change

Show the resolved local URL for easier debugging
![image](https://github.com/user-attachments/assets/f674f5be-33d2-4458-be2c-d56af3f70de7)

Depends on Code PR https://github.com/home-assistant/core/pull/128432

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-10-15 09:57 UTC, piitaya reviewed
We are using a full width alert for cloud alert. Can we use the same UX for that one?

![CleanShot 2024-10-15 at 11 54 28](https://github.com/user-attachments/assets/dfb13a21-f93c-4036-af6b-b0b20772c1ab)

2024-10-15 13:29 UTC, piitaya approved these changes, later dismissed

2024-10-15 15:33 UTC, balloob commented
Can we add a button to copy it to your clipboard?

2024-10-17 14:31 UTC, MindFreeze commented
Made the url inputs always visible with masking when not editing and copy buttons
![image](https://github.com/user-attachments/assets/6cfdd573-b8f0-4192-8661-97f34ab775f2)

2024-10-21 13:29 UTC, matthiasdebaat commented
![CleanShot 2024-10-21 at 15 29 04@2x](https://github.com/user-attachments/assets/d30c3230-0005-4a21-976a-e6aa1af12c0a)

May I suggest the following changes:
- Change the labels Internet and Local into subtitles, to make a clear distinction.
- Move the toggle/switches to the end of the row and move the labels at the beginning. This is the default pattern for switches.
- Change the Automatic label, of Local network,  into something that explains it a bit more. For example Use network settings.
- Add examples to the input when enabled.
- Change the copy link buttons into the text variant, as there can be only one primary button on a page.
- When Home Assistant Cloud is enabled, add a link to the settings.
- Can we add the port number to link?
- Show the ha-alert with a configure button, so that the user can enabled it on the Cloud settings.

2024-10-21 13:41 UTC, MindFreeze commented
I don't think "Use network settings" is more descriptive. "Automatic" tells me I don't need to worry about it.

The port number is included in the link if configured but it is obfuscated with the rest of the url right now. I wondered whether to leave it visible but it's the same level of info as the local address and we obfuscate that

2024-10-21 14:24 UTC, matthiasdebaat commented
> I don't think "Use network settings" is more descriptive. "Automatic" tells me I don't need to worry about 

Lets keep the label Automatic and add a description what this is. So it's easy and gives an insight in the magic box.

> The port number is included in the link if configured but it is obfuscated with the rest of the url right now. I wondered whether to leave it visible but it's the same level of info as the local address and we obfuscate that

If we copy it in the link I would also show the input. We can show it as below for editable and read-only inputs.

![CleanShot 2024-10-21 at 16 24 34@2x](https://github.com/user-attachments/assets/e1fc2bdc-1afd-4ac9-8b49-09d8ffcf20b2)

2024-10-21 16:13 UTC, MindFreeze commented
![image](https://github.com/user-attachments/assets/6b74e24e-3934-477b-97a8-c9b4813df974)

2024-10-23 19:33 UTC, balloob commented
There is no need to censor the internal IP, as it cannot be reached externally.

2024-10-23 19:42 UTC, frenck commented
> There is no need to censor the internal IP, as it cannot be reached externally.

We discussed this, as there actually is a need for it. As in, people with loopback issues van use different URLs, and split DNS peeps will probably use the same as the external URL.

From that perspective, it is hard to make external masked, and internal not.

2024-10-25 12:29 UTC, wendevlin requested changes
Thank you, looks great :tada: 

One main point is missing, disallow empty values.
For both internal and external you come into a strange state when you leave the text input empty and hit save. Please don't allow to hit save when one of them is empty and show a validation info.

2024-10-25 12:48 UTC, MindFreeze commented on src/panels/config/network/ha-config-url-form.ts
> +  private _obfuscateUrl(url: string) {
There only .ui.nabu.casa urls are handled. Here it could be anything so the logic is different

2024-10-25 12:59 UTC, MindFreeze commented
> Thank you, looks great 🎉
> 
> One main point is missing, disallow empty values. For both internal and external you come into a strange state when you leave the text input empty and hit save. Please don't allow to hit save when one of them is empty and show a validation info.

Empty is a valid value. You need to be able to remove the custom urls

2024-10-28 07:16 UTC, wendevlin commented on src/panels/config/network/ha-config-url-form.ts
> +  private _obfuscateUrl(url: string) {
Why can it be anything? It is just masked when I activate HA cloud url, or do I get something wrong?

- When I sign out from HA cloud, I have the external url field always enabled and not masked.
- When I sign in to HA cloud, I get the field with the ha cloud toggle, when I toggle cloud it is masked, when not it is visible as normal.

2024-10-28 07:18 UTC, wendevlin commented
> Empty is a valid value. You need to be able to remove the custom urls

Okay, yeah make sense.
Then please recheck the logic when you clear the url to `""` and then get it with `private get _externalUrlValue()` (or internal)
It always fallback to the `this._urls?.external` when `this._external_url` is falsy. But then you are never able to clear it. After refresh the old value is still there.

---
Something else: we should remove the advanced flag here. The plan is to remove it completely from the settings and at first step by step where it is in use. So this would be the perfect time for the url form :+1:

2024-10-28 09:40 UTC, MindFreeze commented on src/panels/config/network/ha-config-url-form.ts
> +  private _obfuscateUrl(url: string) {
You're right. I was thinking of the internal url that could be anything

2024-10-28 11:23 UTC, wendevlin requested changes

2024-10-28 11:23 UTC, wendevlin commented on src/panels/config/network/ha-config-url-form.ts
> +                placeholder="http://<some IP address>:8123"
We need to translate this.

2024-10-28 11:23 UTC, wendevlin commented on src/util/url.ts
> +  if (url.includes(".ui.nabu.casa")) {
```suggestion
  if (url.endsWith(".ui.nabu.casa")) {
```

2024-10-29 13:57 UTC, wendevlin approved these changes

2024-10-29 14:07 UTC, merged