Use friendly names in turned_on/turned_off notifications.
home-assistant/frontend pull request #224
Opened 2017-02-28 19:28 UTC by andrey-git

Use friendly name in "toast" turned_on / turned_off notifications.
Fixes home-assistant/home-assistant#5388

2017-03-02 07:26 UTC, balloob requested changes

2017-03-02 07:26 UTC, balloob commented on src/home-assistant.html
> +              name = this.hass.states[serviceData.entity_id].attributes.friendly_name;
Not all states will have a friendly name attribute. Please use `window.hassUtil.computeStateName`

2017-03-02 07:26 UTC, balloob commented on src/home-assistant.html
> +          }.bind(this),
I prefer if instead of binding to `this`, we add `var el = this;` before we call `conn.callService`

2017-03-02 09:40 UTC, andrey-git commented on src/home-assistant.html
> +          }.bind(this),
Done

2017-03-03 04:00 UTC, balloob approved these changes

2017-03-03 04:00 UTC, merged