Update more-info dialog layout for weather entities
home-assistant/frontend pull request #22818
Opened 2024-11-13 22:58 UTC by cgarwood

## Proposed change
This updates the more-info dialog for weather entities to more closely match the newer styling of the weather forecast card.

![image](https://github.com/user-attachments/assets/508bcb32-33a6-4ab1-ad09-5e73651d77ea)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2024-11-14 02:39 UTC, cgarwood commented
Added some additional commits to replace the list of attributes with badges. Not 100% sold on it... interested in feedback.

![image](https://github.com/user-attachments/assets/bbbe22c0-1fdb-4ea6-ad44-9919e98f9142)

2024-11-18 19:01 UTC, michaelarnauts commented
The "Forecast:" looks a bit out of place IMHO. I wonder if you could just drop it. It's quite clear that it's a forecast with the dates anyway.

I prefer the list instead of the badges.

Overall, this makes the dialog more stylish, and I think that's a good thing!

2024-11-20 22:02 UTC, cgarwood commented
Switched back to list for attributes. Currently it's truncating the forecasts to 6, but I can work on making them scroll.

2024-11-21 23:00 UTC, cgarwood commented
Forecast will show all  records we have now with a horizontal scroll and fade effect on the edges:
![image](https://github.com/user-attachments/assets/8a4446d0-9b40-4779-bcb5-3487307811c8)

2025-01-29 12:38 UTC, wendevlin requested changes
Thank you, looks good. Just some small comments. 

Can you please fix the merge conflicts?

2025-01-29 12:38 UTC, wendevlin commented on src/dialogs/more-info/controls/more-info-weather.ts
> +  @property({ attribute: false }) public changedOverride?: number;
Why is this here? It's not used

2025-01-29 12:38 UTC, wendevlin commented on src/dialogs/more-info/controls/more-info-weather.ts
> +                : html`&nbsp;`}
```suggestion
                : nothing}
```

2025-01-29 12:38 UTC, wendevlin commented on src/dialogs/more-info/controls/more-info-weather.ts
> +                          : ""}
```suggestion
                          : nothing}
```

2025-01-29 12:38 UTC, wendevlin commented on src/dialogs/more-info/controls/more-info-weather.ts
> +                              ? ""
```suggestion
                              ? nothing
```

2025-01-29 12:38 UTC, wendevlin commented on src/dialogs/more-info/controls/more-info-weather.ts
> +                  : ""
```suggestion
                  : nothing
```

2025-02-06 06:11 UTC, wendevlin approved these changes

2025-02-06 06:11 UTC, merged

2025-09-26 06:47 UTC, shaxxx commented
I'm a bit late to the show, but I've just updated my HASS and most important thing for me is not working anymore.
Previously, hourly forecast would show hour and DAY, not only hour. 
This new layout makes it unusable. If i select daily forecast and I scroll horizontally after few informations I'm lost at what day I'm looking at. And making it horizontal only forces me to scroll and scroll.
We can discuss about what's nice for someone, and what's not, but I don't have the info I had before this change.
And I'm not the only one
https://community.home-assistant.io/t/weather-change-to-horizontal/868329/10