Geo Location Map
home-assistant/frontend pull request #2337
Opened 2018-12-16 09:45 UTC by exxamalte

This is a map card that can not only display manually configured entities, but allows for configuring a `source` which each geo location platform defines. All current geo location entities with that source will be displayed on the map automatically.

Sample card configuration:
```
type: geo-location-map
source: nsw_rural_fire_service_feed
entities:
  - zone.home
default_zoom: 9
```

<img width="502" alt="lovelace-geo-location-map" src="https://user-images.githubusercontent.com/4704260/50052116-40b54880-0173-11e9-9fef-b37a583cc4c1.png">

2018-12-16 10:12 UTC, exxamalte commented
Hold on, I just realised that `entities` is required, but instead `source` should be required and `entities` optional.

2018-12-16 10:29 UTC, iantrich commented
We have a map card. Why would you not at least add this source to the existing rather than copy all its code to a new file to add it?

2018-12-16 10:37 UTC, exxamalte commented
Sure, happy to do that as well. I'm just wondering how to untangle which config parameters are then required and which ones are optional: The default map requires `entities` to be set, while the geo location map requires `source` to be set and additional `entities` are optional.

2018-12-16 21:53 UTC, exxamalte commented
> Geo location sources should probably be an array?

Good point, because that would be the only way to join entities from different geo location platforms into one map.

2018-12-17 06:54 UTC, balloob requested changes

2018-12-17 06:54 UTC, balloob commented on src/panels/lovelace/cards/hui-map-card.js
> +    var allEntities = [];
Doing use var

2018-12-17 06:54 UTC, balloob commented on src/panels/lovelace/cards/hui-map-card.js
> +    this._configGeoLocationSources = config.geo_location_sources;
Don't assign before raising errors

2018-12-17 08:04 UTC, balloob approved these changes

2018-12-17 08:04 UTC, merged

2018-12-17 08:07 UTC, balloob commented
Do you want to submit a PR to add this functionality to a map demo ?

2018-12-17 10:46 UTC, exxamalte commented
> Do you want to submit a PR to add this functionality to a map demo ?

Sure. I'll take a look at that now...

2018-12-30 09:56 UTC, frenck commented
Just a note @exxamalte, `geolocation` is one word. So, it should be `geolocation_sources`...

2019-01-20 21:18 UTC, thomasloven commented
@exxamalte I cannot find any documentation for this. Do you have something prepared, or should I add it when I'm documenting #2489 ?

2019-01-20 22:56 UTC, exxamalte commented
@thomasloven The documentation for this PR can be found here: https://github.com/home-assistant/home-assistant.io/pull/7880