Add feature to rename multiple related entities at once
home-assistant/frontend pull request #2957
Opened 2019-03-17 17:21 UTC by gkreitz

After installing some fibaro switches, I wanted to more conveniently rename them (each switch generates a ton of entities - zwave, switch/light, sensors). According to forum threads (e.g., https://community.home-assistant.io/t/what-is-the-preferred-way-to-rename-z-wave-entities/64329/151), it seemed like the entity registry was the preferred route to go. So I added a small feature where, when one edits a device, a heuristic is applied to find related entities and offer a way to rename all related entities at once. The heuristic for matching entities is:
- Friendly name of clicked device is a substring of friendly name of matching entity
- Suffix of entity_id (after last period) is a substring of entity_id of matching entity

Demo gif: https://gfycat.com/HospitableCluelessGoldenmantledgroundsquirrel

Apologies for the questionable code quality, think of this more as a feature request with a proof-of-concept PR. I don't normally do much javascript/frontend, and this was my first time encountering typescript and polymer, so there's a fair bit of cargo culting in this PR. In particular, the way I handle clicks on checkboxes feels far from optimal, and I didn't find a good container to surround matching entities with, so they jump around a bit when editing.

2019-03-17 17:21 UTC, homeassistant commented
Hi @gkreitz, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#2957).

Once you do that we will be able to review and accept this pull request.

Thanks!

2019-03-18 03:35 UTC, balloob commented on src/panels/config/entity_registry/ha-config-entity-registry.ts
> +    const matchingEntities = this._items.filter((e) => {
Instead of matching like this, we should find all entitty registry entries that have the same device_id as the one picked.

2019-03-18 03:38 UTC, balloob requested changes
This is a good idea.

However, please do not add this to the existing dialog for config entries, as it prevents us from growing the functionality out without applying it to all entities too. 

This should be a new dialog (ok to copy paste).

I think that we can have a toggle to turn on "multi-entity editor mode" or whatever in the description part.

2019-03-18 07:28 UTC, gkreitz commented
Thanks for the feedback!

Before I copy-paste things around, I just want to double-check. My thinking (without knowing this code base at all) was that it’s better to not create a new dialog to avoid code duplication. Note that the added feature is completely controlled by the new parameter `matchingEntities[]`. If one supplies an empty array there, the dialog is unaffected. Does that address your concerns with having this in the existing dialog?

> On 18 Mar 2019, at 04:38, Paulus Schoutsen <notifications@github.com> wrote:
> 
> @balloob requested changes on this pull request.
> 
> This is a good idea.
> 
> However, please do not add this to the existing dialog for config entries, as it prevents us from growing the functionality out without applying it to all entities too.
> 
> This should be a new dialog (ok to copy paste).
> 
> I think that we can have a toggle to turn on "multi-entity editor mode" or whatever in the description part.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/home-assistant/home-assistant-polymer/pull/2957#pullrequestreview-215407341>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AELDK6aWxWfi9mcP_ipNXVRgrvDGpH8jks5vXworgaJpZM4b4hew>.
>

2019-03-18 17:04 UTC, balloob commented
I don't want to have it in the existing dialog, it will be a burden for extending that dialog. 

I also have been thinking, this is better suited for a device registry page, as all those entities are connected to a device. So when a user renames a device, offer to update all entities too. 

We just don't have a device registry page yet, but all WS commands are there.

2019-03-18 17:17 UTC, gkreitz commented
I agree that a new device registry pace would be a more logical place to fit this type of functionality. Didn't know one was planned. Closing this PR.

Thanks for looking at the PR! Was a fun learning experience to play with typescript/polymer, and the hack solved my immediate problem.

2019-03-18 17:17 UTC, closed without merging