WIP: Prevent multiple submission
home-assistant/frontend pull request #3155
Opened 2019-05-03 08:27 UTC by awarecan

Might fixes #3118

2019-05-03 09:18 UTC, thomasloven requested changes

2019-05-03 09:18 UTC, thomasloven commented on src/onboarding/ha-onboarding.ts
> +    ev.preventDefault();
`ev` is not a parameter of `_submitForm()`. This will be an error.

2019-05-03 09:18 UTC, thomasloven commented on src/panels/config/users/ha-dialog-add-user.js
> +    ev.preventDefault();
Same thing here.

2019-05-03 09:26 UTC, awarecan commented
@thomasloven I won't have time to actually run it in next few days, feel free to edit it. That is why I mark it WIP.

2019-05-08 05:28 UTC, balloob commented
I do a lot of testing in FF and have never been able to reproduce this.

2019-05-08 06:55 UTC, awarecan commented
Close in favor of #3172

2019-05-08 06:55 UTC, closed without merging