Initial themes support
home-assistant/frontend pull request #331
Opened 2017-07-09 19:47 UTC by andrey-git

Initial themes support.
Backend support: https://github.com/home-assistant/home-assistant/pull/8419
For now loads themes once on UI load.
In order to change a theme call `frontend.set_default_theme` to set theme on backend and reload the UI.

2017-07-10 13:23 UTC, andrey-git commented
I wonder if themes should be subscribable, like states, so a change in backend would immediately show in frontend.

I think that if we do want this, maybe themes better be a component (and either a single entity object, or also entity per theme). Then it would be exposed via the existing states subscription.

2017-07-10 18:28 UTC, balloob commented
`hass.connection` is the websocket connection. You can subscribe to `themes_updated` events and just fire those in the backend. 

https://github.com/home-assistant/home-assistant-js-websocket#connsubscribeeventseventcallback-eventtype

2017-07-10 19:33 UTC, andrey-git commented
How do I work with edited home-assistant-js-websocket?

2017-07-11 00:34 UTC, balloob commented
In the checked out repo with your changes run `yarn link`. Make sure you are also building the dev version with `yarn watch`.

In the home-assistant-polymer repo run `yarn link home-assistant-js-websocket`.

Event subscription is already available, so why would you make a change?

2017-07-11 01:48 UTC, balloob commented on src/layouts/home-assistant-main.html
> +  _hassChanged: function (hass) {
Instead of checking on each hass change, do this on `attached` event.

2017-07-11 01:55 UTC, balloob commented on src/layouts/home-assistant-main.html
> +          _this.customStyle['--' + key] = value;
Don't use customStyle. Pass the values into `updateStyles` instead: https://www.polymer-project.org/2.0/docs/upgrade#use-updatestyles-instead-of-customstyle

2017-07-11 02:00 UTC, balloob commented on src/layouts/home-assistant-main.html
> +        if (result.current_theme === 'default') return;
We should still set the theme when it is `default` ?

2017-07-11 19:27 UTC, andrey-git commented on src/layouts/home-assistant-main.html
> +  _hassChanged: function (hass) {
`attached` didn't fire for some reason, so I put it in `ready`.

2017-07-11 19:28 UTC, andrey-git commented on src/layouts/home-assistant-main.html
> +          _this.customStyle['--' + key] = value;
Done

2017-07-11 19:28 UTC, andrey-git commented on src/layouts/home-assistant-main.html
> +        if (result.current_theme === 'default') return;
Added a record of all set styles, so that extra styles can be cleared.

2017-07-13 01:15 UTC, balloob commented on src/layouts/home-assistant-main.html
> +      themes => window.hassUtil.applyThemesOnElement(_this, themes));
Only ES5 syntax please. We don't have transpilation setup yet.

2017-07-13 01:16 UTC, balloob commented on src/layouts/home-assistant-main.html
> +      event => window.hassUtil.applyThemesOnElement(_this, event.data),
Same.

2017-07-13 01:17 UTC, balloob requested changes
Ok to merge once comments addressed

2017-07-13 06:46 UTC, andrey-git commented on src/layouts/home-assistant-main.html
> +      themes => window.hassUtil.applyThemesOnElement(_this, themes));
Done

2017-07-13 06:46 UTC, andrey-git commented on src/layouts/home-assistant-main.html
> +      event => window.hassUtil.applyThemesOnElement(_this, event.data),
Done

2017-07-13 16:10 UTC, balloob approved these changes

2017-07-13 16:11 UTC, merged