Removed disable buttons
home-assistant/frontend pull request #356
Opened 2017-07-25 17:21 UTC by cdce8p

Allow commands being send even if cover is open or closed. Important for cover template when using multiple covers or in end positions when cover registered as open/closed but isn't due to tolerance.

Example for multiple covers: https://github.com/home-assistant/home-assistant.github.io/pull/3013

2017-07-25 17:21 UTC, homeassistant commented
Hi @cdce8p, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#356).

Once you do that we will be able to review and accept this pull request.

Thanks!

2017-07-25 17:44 UTC, andrey-git commented
I think the disabled buttons are nice.

I don't think the 1st reason is valid. A proper implementation would be using `position_template` to be an average or median of all the covers - then "all covers" would be half-open unless all covers are open/closed.
 
The 2nd reason is valid though, but maybe it should be configurable ;)

2017-07-25 20:30 UTC, cdce8p commented
@andrey-git In my option the ˋcover templateˋ is more a not ideal workaround for controlling more than one cover and the fix above would have been the easiest solution. I haven't jet tried the ˋposition_templateˋ, but my understanding thus far is that it would be vastly more complex.

I personally wouldn't mind having the buttons always enabled, that's why I proposed the change. I would certainly be ok with this being an option in the config. Another idea could be to also display the position next to the controls (also as an configurable).

I will see if I get this to work in the next few days and later maybe and own compontent to control multiple covers.

2017-07-26 04:00 UTC, balloob commented
We should not remove the disabled state, it's a nice indicator on the state of the cover. We also should not decrease functionality for other platforms to add support for "a not ideal workaround for controlling more than one cover".

However, what would be fine is that when `assumed_state` is set to True, we don't disable any button.

2017-07-27 17:17 UTC, andrey-git commented on src/components/ha-cover-controls.html
> +      <template is='dom-if' if='[[!entityObj.assumeState]]'>
Instead of duplicating the dom element - make a function that will decide whether the button should be disabled.

2017-07-29 06:19 UTC, balloob requested changes

2017-07-29 06:19 UTC, balloob commented on src/util/cover-model.html
> +  addGetter('disableButtonFullyOpen', function () {
We should not add these to the cover model as they are very specific to the component where they are used. They should be computed inside the component instead.

2017-07-29 06:19 UTC, balloob commented on src/components/ha-cover-controls.html
> +        disabled='[[entityObj.disableButtonFullyClosed]]'></paper-icon-button>
Don't add this to entityObj. Compute it in component instead: `disabled='[[computeCloseDisabled(stateObj, entityObj]]'

2017-07-29 17:23 UTC, balloob approved these changes

2017-07-29 17:23 UTC, merged

2017-07-29 17:23 UTC, balloob commented
🎉  thanks