Variable cards and background colours
home-assistant/frontend pull request #361
Opened 2017-07-27 11:30 UTC by ahofelt

First contribution, apologies for any mistakes.
As discussed in the "Share your Themes thread": https://community.home-assistant.io/t/share-your-themes/22018/9?u=ahs.

Goal is to allow more flexibility with theming (allowing e.g. "night mode") by replacing some hardcoded values by variable colours (which can be defined in custom themes):

* replaced the white background colour in the state cards (ha-card.html) by the variable background colour
* replaced the light grey overall background colour by the variable paper-grey-200 colour

Note that the default paper-grey-200 is not exactly the same as the current colour (#E5E5E5) but is the closest match of the defined colours in ha-style.html. It will however lead to a slight recolouring of the default background.

2017-07-27 11:30 UTC, homeassistant commented
Hi @ahofelt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#361).

Once you do that we will be able to review and accept this pull request.

Thanks!

2017-07-27 11:48 UTC, andrey-git commented on src/components/ha-card.html
> +        background-color: var(--primary-background-color);
Lets keep default values:
`background-color: var(--primary-background-color, white);`

2017-07-27 11:48 UTC, andrey-git commented on src/layouts/partial-cards.html
> +        background-color: var(--paper-grey-200);
Create a separate variable.
If you want a green background here you wouldn't want to override `paper-grey-200` to green,

2017-07-27 12:05 UTC, ahofelt commented
You're right @andrey-git changed it now as you suggested. Added a `--secondary-background-color` definition now in ha-style.html and referenced that one instead of `--paper-grey-200`. Also added the default colours for both.

2017-07-27 12:13 UTC, bramkragten commented
If you want a proper dark theme you would need a few more adjustments, I don't have a fork right now so maybe you want to add this?

in ha-sidebar:
add to : host
background: var(--paper-listbox-background-color,var(--primary-background-color));

in home-assistant-main add:
color: var(--primary-text-color)

in ha-panel-dev-service change:
.attributes tr:nth-child(even) {
  background-color:#eee
}
to:
.attributes tr:nth-child(even) {
  background-color: var(--paper-listbox-background-color,#eee) (or a new one?)
}

ha-state-icon:
color: var(--paper-item-icon_-_color, #44739e)
I believe there is another one for active/on, that would need to be changed as well.

The svg in state-history-chart-timeline might need some... for example:
fill="var(--paper-dialog-background-color,var(--primary-background-color))" for the main rect... and
fill="var(--primary-text-color)" for the times underneath...

I think that would bring us pretty close. A few more thing to do in specific components probably.

2017-07-27 12:29 UTC, bramkragten commented
ha-media_player-card

.controls {
...
    background-color: var(--same as ha-card);
}
ha-state-label-badge would need some updates...

2017-07-27 12:32 UTC, ahofelt commented
@bramkragten : Ok, going through them now -- but unsure on your `home-assistant-main` point. There's not a lot of styling in there.. https://github.com/home-assistant/home-assistant-polymer/blob/master/src/layouts/home-assistant-main.html

2017-07-27 12:35 UTC, bramkragten commented
Thats for all the text that does not have explicit styling, it now just takes the browser default which is black, we would need to set a text color at some high point, normally you would juse the body. But figgered home-assistant-main was high enough and there the custom styles are set aswell... So I would suggest adding a style block? @andrey-git suggestions?

2017-07-27 12:44 UTC, ahofelt commented
As to ha-state-icon, the active state is actually in state-badge.html (currently: #44739E) and the inactive is somewhere in bower_components/paper-dialog/paper-dialog.html (isn't that outside our reach?).
The --paper-item-icon_-_color you suggest is not defined, I think, so it will resort to #44739E which causes the change not to do anything.

2017-07-27 12:50 UTC, bramkragten commented
That would mean we could just define --paper-item-icon_-_color in our styles config, let me try that.

State badge is found here:
https://github.com/home-assistant/home-assistant-polymer/blob/a1057681f1a33cffc79708085c1646d786712a87/src/components/entity/state-badge.html

2017-07-27 12:55 UTC, ahofelt commented
> State badge is found here:

Yes, that's where it is defined as #44739E

I added some more changes as you suggested. As to the changes in home-assistant-main, state-history-chart-timeline, and ha-state-icon/state-badge, I'm afraid that's beyond me for now..

2017-07-27 18:18 UTC, bramkragten commented
The charts are a different story indeed, Google charts makes them, I believe you can set options with colors, but I'm not familiair with it. Also not the biggest problem right now.

I'll look at the points left. Have to setup a development environment for the frontend...

2017-07-27 22:59 UTC, bramkragten commented
For the state cards, I would prefer a different variable; paper-card-background-color. 
So I can give them a different color then the background.

Thanks for your work btw. I have my def env setup, tomorrow I'll get on to this.

2017-07-28 07:59 UTC, ahofelt commented
> For the state cards, I would prefer a different variable; paper-card-background-color.
>So I can give them a different color then the background.

Yes that makes sense. Changed the previous `secondary-background-color` to `paper-card-background-color` now both in the styles and the state cards.

Furthermore, I externalized the label colours (added `--label-red`, `--label-blue`, etc. in ha-style.html and changed the hardcoded colours in ha-state-label-badge.html to these` var(--label-red`), `var(--label-blue)`, etc. variables. This way, we can include label colours in our theming.

Question to someone more proficient than I: would it be possible to add something to customize the colour of the label in the config file? Currently it's coded to display red at all times except for the `binary_sensor` and `updater` (and the demo but that's another case). It would be neat to be able to define this in the config file in the customize section. But maybe that's a step too far at this stage.

2017-07-28 09:41 UTC, marksev1 commented
Can someone please add a screenshot on how such a dark ui would look like after these things will be merged? Would be super nice to see if a suitable night theme could be made using these changes :)

2017-07-28 09:49 UTC, ahofelt commented
> Can someone please add a screenshot on how such a dark ui would look like after these things will be merged? Would be super nice to see if a suitable night theme could be made using these changes :)

Sure, I've added two screenshots of my current setup in the "Share your Themes" thread on the community forums: https://community.home-assistant.io/t/share-your-themes/22018/21

2017-07-28 09:56 UTC, bramkragten commented
@marksev1 And another one here https://community.home-assistant.io/t/dark-theme-or-night-mode-theme/446/33

2017-07-28 11:18 UTC, marksev1 commented
Very nice guys! I especially like yours bramkragten :). So it think I'm just gonna replace the files by hand :) that I also have this goodness :).

2017-07-28 11:27 UTC, ahofelt commented
> Question to someone more proficient than I: would it be possible to add something to customize the colour of the label in the config file? Currently it's coded to display red at all times except for the binary_sensor and updater (and the demo but that's another case). It would be neat to be able to define this in the config file in the customize section. But maybe that's a step too far at this stage.

To answer my own question a bit earlier, I suppose we could use this pretty ugly code in /components/entity/ha-state-label-badge.html to base the labels' colours off the unit of measurement. It suits my own goal to colour the temperature sensors differently from the humidity sensors. But it's not the most elegant solution...

`  computeClasses: function (state) {`
`    switch (window.hassUtil.computeDomain(state)) {`
`      case 'sensor':`
`      case 'binary_sensor':`
`        if (state.attributes.unit_of_measurement === '°C' || state.attributes.unit_of_measurement === '°F') {`
`          return '';`
`        } else if (state.attributes.unit_of_measurement === '%') {`
`          return 'blue';`
`        } else {`
`          return 'grey';`
`        }`
`      case 'updater':`
`        return 'yellow';`
`      case 'device_tracker':`
`        return 'green';`
`      case 'sun':`
`        return 'yellow';`
`      default:`
`        return '';`
`    }`
`  },`

2017-07-28 18:18 UTC, bramkragten reviewed
I'm gonna look at the other things now!

2017-07-28 18:18 UTC, bramkragten commented on panels/dev-service/ha-panel-dev-service.html
> +        background-color: var(--paper-listbox-background-color,#eee)
Actually we should use a different variable here, something like: 
--table-row-alternative-background-color

And maybe add:

.attributes tr:nth-child(odd) {
         background-color: var(--table-row-background-color)
}

 We should also change that in dev-state.

2017-07-28 18:18 UTC, bramkragten commented on src/cards/ha-media_player-card.html
> +        background-color: var(--primary-background-color, white);
Use --paper-card-background-color

2017-07-28 18:18 UTC, bramkragten commented on src/components/ha-card.html
> +        background-color: var(--primary-background-color, white);
This should be --paper-card-background-color, as this is the card.

2017-07-28 18:18 UTC, bramkragten commented on src/layouts/partial-cards.html
> +        background-color: var(--paper-card-background-color, #E5E5E5);
Use --secondary-background-color here.

2017-07-28 19:18 UTC, bramkragten commented
See: https://github.com/bramkragten/home-assistant-polymer/commit/b976466374302064e0303a29320a8ed8378ce425

2017-07-29 06:07 UTC, balloob requested changes

2017-07-29 06:07 UTC, balloob commented on panels/dev-service/ha-panel-dev-service.html
> +        background-color: var(--paper-listbox-background-color,#eee)
I agree.

We should have hierarchical variable declarations.

 - Colors: ie `--google-grey-200`, red, blue etc
 - Brand variables: ie `--primary-color`, `--accent-color`
 - Applied colors: `--table-row-alternative-background-color`, `--table-row-background-color`

Only the last two categories should be used to style things. We should also make sure that users don't have to override variables by Google like `--paper-listbox-background-color`.

2017-07-29 06:07 UTC, balloob commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-red);
Label is ambiguous. Let's do `--label-badge-red`.

2017-07-29 06:07 UTC, balloob commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-blue);
idem

2017-07-29 06:07 UTC, balloob commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-green);
idem

2017-07-29 06:07 UTC, balloob commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-grey);
idem

2017-07-29 08:42 UTC, bramkragten commented
@balloob I think it would be cool to able to set a theme by just setting these base variables (don't look at the values):

    --primary-color: #03A9F4;
    --dark-primary-color: #0288D1;
    --light-primary-color: #B3E5FC;
    --primary-text-color: #212121;
    
    --secondary-color: #03A9F4;
    --dark-secondary-color: #0288D1;
    --light-secondary-color: #B3E5FC;
    --secondary-text-color: #727272;

Those colors could be easily get from [material.io/color](https://material.io/color/#!/?view.left=0&view.right=0&primary.color=03A9F4&secondary.color=D7CCC8) for example.

The other vars would still be adjustable if you want to, but if you don't they are inherited from one of the base colors.

That would mean however that the current color's of the front-end would change a little at some points, as there are more colors defined right now.

Is that an option, or should the current color scheme be unchanged?

2017-07-29 12:16 UTC, ahofelt commented on src/layouts/partial-cards.html
> +        background-color: var(--paper-card-background-color, #E5E5E5);
Hmm I took out `--secondary-background-color` yesterday and replaced this one by `--paper-card-background-color`. Shall I put it back? Currently `--secondary-background-color` is not defined in the styles anymore.

2017-07-29 12:27 UTC, ahofelt commented on panels/dev-service/ha-panel-dev-service.html
> +        background-color: var(--paper-listbox-background-color,#eee)
Ok, changed this now. So we also now need to define `--table-row-alternative-background-color` and `--table-row-background-color` in ha-style.html, right?

2017-07-29 12:27 UTC, ahofelt commented on src/cards/ha-media_player-card.html
> +        background-color: var(--primary-background-color, white);
done

2017-07-29 12:27 UTC, ahofelt commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-red);
Done. Also added the old colour (html-ified it to #DF4C1E) as second option. Furthermore added a special line that explicitly defined class .red as red, and added .yellow badge colour. Currently not used but can be in the future.

2017-07-29 12:27 UTC, ahofelt commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-blue);
Done

2017-07-29 12:27 UTC, ahofelt commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-green);
Done

2017-07-29 12:27 UTC, ahofelt commented on src/components/entity/ha-state-label-badge.html
> +        --ha-label-badge-color: var(--label-grey);
Done

2017-07-29 12:27 UTC, ahofelt commented on src/components/ha-card.html
> +        background-color: var(--primary-background-color, white);
Done

2017-07-29 12:38 UTC, ahofelt commented
Ok -- all suggested edits applied and tested.

2017-07-29 13:11 UTC, ahofelt commented
How do we feel about badges? `/src/components/ha-label-badge.html`? The container part that is, which we didn't address yet..

- I think we should replace the background-color for sure to `background-color: var(--paper-card-background-color, white);`, so that it doesn't light up as white under all circumstances. 
- However, and here it's getting more a matter of taste, we can replace the text colour to the default border colour (`color: var(--ha-label-badge-color);`), instead of the current hardcoded colour (`color: rgb(76, 76, 76);`).
- And next, and here it's even more a matter of taste, what about changing it from a round badge (`border-radius: 50%;`) to a more iOS-like form (`border-radius: 33%;`)? It gives more room for the icon inside and IMHO just looks a bit more modern.

Here's a preview, white and dark backgrounds:
<img src="https://image.ibb.co/hPQNh5/Capture.png" alt="Capture" border="0" />
<img src="https://image.ibb.co/krwdN5/Capture.png" alt="Capture" border="0" />

2017-07-29 17:36 UTC, balloob commented
@ahofelt it looks like you're editing this via the GitHub online editor. Please test this locally.

2017-07-29 17:37 UTC, balloob commented
@bramkragten the problem is that CSS variables does not have functions that SASS has like `lighten` or `darken`.

2017-07-30 07:40 UTC, ahofelt commented
> @ahofelt it looks like you're editing this via the GitHub online editor. Please test this locally.

@balloob yes that's correct. I'm just a beginner and have my difficulties in understanding it all. But I do test it all locally before mirroring the changes manually in the GitHub online editor. Not the most efficient way but it works for me for now. Triple-checked everything for consistency. All working perfectly well locally. And most of the recent changes have been suggested by @bramkragten and I merely copy (and test) them. Apologies for my ignorance.

2017-08-01 06:08 UTC, balloob commented
Alright, tested it locally and didn't see anything of the default theme be off, so fine with me 👍

2017-08-01 06:08 UTC, balloob approved these changes

2017-08-01 06:09 UTC, merged

2017-08-01 12:07 UTC, ahofelt commented
Wonderful news. Thanks all, @balloob and especially @bramkragten. Now, let's get theming!