Add 7 new icons to weather card and forecast conditions
home-assistant/frontend pull request #3726
Opened 2019-09-15 20:57 UTC by outon

I have noticed that there are new icons in MDI relating to weather conditions.

I propose the inclusion of these new icons.

2019-09-15 20:57 UTC, homeassistant commented
Hi @outon, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant-polymer#3726).

Once you do that we will be able to review and accept this pull request.

Thanks!

2019-09-15 21:44 UTC, iantrich requested changes
Should be good after comments addressed

2019-09-15 21:44 UTC, iantrich commented on src/cards/ha-weather-card.js
> +      'hazy': "hass:weather-hazy",
Quotes not needed on hazy

2019-09-15 21:44 UTC, iantrich commented on src/panels/lovelace/cards/hui-weather-forecast-card.ts
> +  'hazy': "hass:weather-hazy",
Quotes not needed on hazy

2019-09-16 05:27 UTC, Mariusthvdb commented
could it be possible to also add the icon mdi:weather-night for condition clear-night?
see https://github.com/home-assistant/home-assistant/pull/26452#event-2613722551 where we added this for the dark sky sensor.

Not sure if this condition is returned in the weather forecast card conditions, but we do need a way to distinguish clear-night from a bright shining sun on the weather forecast cards.

2019-09-16 05:43 UTC, outon commented
> great to see these added, thanks for that!
> could it be possible to also add the icon mdi:weather-night for condition clear-night?
> see [home-assistant/home-assistant#26452 (comment)](https://github.com/home-assistant/home-assistant/pull/26452#event-2613722551) where we added this for the dark sky sensor.

I see that your  [request](https://github.com/home-assistant/home-assistant/pull/26452#event-2613722551) seems to be already merged, probably on near future version will apear.

2019-09-16 11:52 UTC, bramkragten commented
I think we can include these new icons, but I think more needs to be updated:

- The dev docs for supported states: https://developers.home-assistant.io/docs/en/entity_weather.html#recommended-values-for-state-and-condition
- Translations: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/translations/en.json#L281

And we should have at least one weather component that uses these new states/icons.

2019-09-16 14:12 UTC, outon commented
> * The dev docs for supported states: https://developers.home-assistant.io/docs/en/entity_weather.html#recommended-values-for-state-and-condition

I have created a pull request on that repository: https://github.com/home-assistant/developers.home-assistant/pull/315

> * Translations: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/translations/en.json#L281

I have included all new weather conditions to translation file

> And we should have at least one weather component that uses these new states/icons.

I am creating a new AEMET custom component which will use them. I do not know about other official weather components. But I guess that once they have those new weather condition they will start using it.

2019-09-16 19:16 UTC, balloob requested changes
New weather conditions first need to be proposed and approved in the architecture repo: https://github.com/home-assistant/home-assistant/pull/

2019-09-19 00:24 UTC, MatthewFlamm commented
I think the explosion of subtle variational themes should not be included.  It is too much of a burden to maintain when and if these icon names change or are removed. I would like to see some icons for different conditions like hurricane however.


https://github.com/home-assistant/architecture/issues/263

I started a similar request above recently to use for the recently merged nws integration. It didn't get much traction and `exceptional` wasn't supported at that time.
 Here are the list of unmapped conditions for nws integration that are currently in `exceptional`, as inspiration for meeting @balloob suggestion to have one integration support the icon, I.e. these could be remapped to a new icon. `partlycloudy-night` could also be supported fairly easily in nws and would be a good addition.

```
"Tornado",
"Hurricane conditions",
"Tropical storm conditions",
"Dust",
"Smoke",
"Haze",
"Hot",
"Cold"
```

2019-09-20 21:55 UTC, Mariusthvdb commented
> New weather conditions first need to be proposed and approved in the architecture repo: https://github.com/home-assistant/home-assistant/pull/

would weather-night and weather-night-partly-cloudy be considered new conditions? Hope they are as old as night and day ;-) 
this shouldn't be possible/necessary at midnight:

![Schermafbeelding 2019-09-20 om 23 43 59](https://user-images.githubusercontent.com/33354141/65360899-f67d5e00-dc01-11e9-9f08-35d602be57db.png)

this is more like it:

![Schermafbeelding 2019-09-20 om 23 44 06](https://user-images.githubusercontent.com/33354141/65360916-039a4d00-dc02-11e9-8b87-8da04e3b9b1b.png)

so please lets use:
![Schermafbeelding 2019-09-20 om 23 48 33](https://user-images.githubusercontent.com/33354141/65360928-0eed7880-dc02-11e9-95e3-51ac3d181c7a.png)

2019-10-13 11:19 UTC, bramkragten commented
Going to close this for now.

2019-10-13 11:19 UTC, closed without merging