WIP: add an input_datetime
home-assistant/frontend pull request #418
Opened 2017-09-05 18:47 UTC by tinloaf

This accompanies the PR adding an 'input_datetime': See https://github.com/home-assistant/home-assistant/pull/9313

I'm not yet really sure when to store a value as string (as in case of the date, since the date picker likes its data as string) and when in some other form (as for the time picker, which likes hours and minutes as numbers). Also, my JavaScript and HTML are probably horrible. I welcome all suggestions for improvement!

2017-10-03 04:17 UTC, balloob requested changes

2017-10-03 04:17 UTC, balloob commented on src/more-infos/more-info-input_datetime.html
> +Polymer({
Please convert this to a Polymer 2 class.

2017-10-03 04:17 UTC, balloob commented on src/util/hass-util.html
> +    } else if (window.hassUtil.computeDomain(stateObj) === 'input_datetime') {
Let's cache the domain in a local variable instead of computing it twice

2017-10-03 14:31 UTC, andrey-git commented on src/more-infos/more-info-input_datetime.html
> +    hass: {
For properties with just the type - use the short syntax:
```
hass: Object
```

2017-10-03 14:31 UTC, andrey-git commented on src/more-infos/more-info-input_datetime.html
> +    <div class$='[[computeClassNames(stateObj)]]'>
You are not styling anything according to those classes

2017-10-03 14:31 UTC, andrey-git commented on src/more-infos/more-info-input_datetime.html
> +    var minuteFiller;
ES6 style: let / const instead of var

2017-10-14 10:43 UTC, tinloaf commented
I have converted the element to a Polymer 2 class now, however there are some things of which I'm not sure whether I solved them 'correctly':

- The is_ready flag seems to be a hack to me, but as far as I can see the lifecycle of a polymer 2 class does not allow to check whether an 'attribute changed' callback fires because of actual user interaction or because initial values are being set. Likewise, at least the vaadin-date-picker element does not seem to have a 'on_change' attribute.

-  Sometimes it seems like I cannot open the date picker dialog or change the time while the history is still loading. Both the date picker and the time picker are just not responding to user interaction while the circle still spins…

2017-10-16 06:51 UTC, balloob commented
Why not listen to `value-changed` on the date picker? [Date picker docs](https://www.webcomponents.org/element/vaadin/vaadin-date-picker/elements/vaadin-date-picker#events)

2017-10-18 19:19 UTC, tinloaf commented
@balloob it low listens to value-changed. I didn't see the value-changed event for the date picker, because it's not listed under the events. :-) Thanks for the hint!

However, there is no such event for the time picker, thus I'm still using the value observers for that.

2017-10-25 06:17 UTC, balloob commented
Nice :dolphin: 🌮

2017-10-25 06:17 UTC, balloob approved these changes

2017-10-25 06:17 UTC, merged