Improve language detection
home-assistant/frontend pull request #561
Opened 2017-11-04 14:06 UTC by c727

* Generalization already handled by navigator.languages
* Detection for Chinese users

Additional information:
In browser settings you can select these tags for Chinese, you can't set custom tags like `zh-Hant...`:
```
tag     Crome   Firefox
zh-CN     X         X
zh-HK     X         X
zh-SG               X
zh-TW     X         X
zh        X         X
```

2017-11-06 16:06 UTC, emlove requested changes
You keep mentioning LOCALE. Can you please provide some information about this? Everything I've found says that this is BCP47.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

https://www.w3.org/TR/html51/webappapis.html#language-preferences

2017-11-06 16:06 UTC, armills commented on src/util/hass-translation.html
> -  const lookup = {};
Don't remove the case insensitive lookup

2017-11-06 16:06 UTC, armills commented on src/util/hass-translation.html
> -    for (let i = subtags.length; i >= 1; i--) {
Don't remove the matching of more general translations. You're breaking a preference of `en-US` matching `en`, etc.

2017-11-06 16:07 UTC, armills commented on src/util/hass-translation.html
> -    for (let i = subtags.length; i >= 1; i--) {
Not all browsers implement a complete navigator.languages. We need to support browsers that only provide one option.

2017-11-06 17:08 UTC, c727 commented
@armills 
I tested this with changing language in browser settings or system language.

See my posts:
https://github.com/home-assistant/home-assistant-polymer/issues/520#issuecomment-341093798
https://github.com/home-assistant/home-assistant-polymer/issues/498#issuecomment-341167047

I don't know if the official name is LOCALE but browsers have no script-subtag

Your concern about navigator.language(s):
* Browsers that don't support languages also won't support Polymer or Service Workers
* Afaik from my tests only Chinese (and maybe other with different scripts) tags have country subtag in navigator.language.
```
navigator.languages[0] = "de-DE"
navigator.language = "de"
```

2017-11-06 17:53 UTC, c727 commented
* I only tested Chrome and Firefox for navigator.languages. Maybe our users can help here or @andrey-git can say more about this.
* as I wrote in one of the issues: even our implementation is not 100% BCP47 compliant as we don't respect extended-language-substags but it's OK for LOCALE
* here is a scenario where the current detection will fail all in all: Let's say my languages = `["en-CA", "en-US", "en"]` and we have no translation for `en-CA`. So it will pick `en` instead of `en-US`

2017-11-06 18:00 UTC, armills commented
1. Here's the compatibility table for https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages#Browser_compatibility . The best proof would be to find a feature we already use that also breaks the browsers we'd be dropping.
2. I agree we aren't handling it completely correctly. Changes that support it better are welcome.
3. I agree that's not good. Moving that substring logic to https://github.com/home-assistant/home-assistant-polymer/pull/561/files#diff-728281481118ad2715d5d4c85eb8059dR38 should let us keep backwards compatibility, but still do a better job with browsers that support navigator.languages.

2017-11-06 20:24 UTC, c727 commented
Here some tests. Maybe we should add regression only for `navigator.language` ... or we kill auto detection on Opera Mobile. Would be great if someone can report for Safari (Mobile)

```
Browser       navigator.languages    navigator.language   Home Assistant

Desktop:
Chrome 62           OK                      de                 OK
Firefox 56          OK                      de                 OK
Opera 48            OK                      de                 OK     
Internet Exp 11     -                       de-DE              -
Edge 38             -                       de-DE              -

Android:
AOSP Browser        -                       de-DE              -
Chrome 61           OK                      de                 OK 
Firefox 56          OK                      de-DE              OK
Opera 43            -                       de-DE              OK
```

2017-11-06 20:31 UTC, armills commented
I like the plan of moving that extra parsing logic to only `navigator.language`. We should trust that the results we get from `navigator.languages` include correct fallback priorities.

2017-11-06 21:19 UTC, armills commented on src/util/hass-translation.html
> +    if (navigator.language.length > 2) {
Don't depend on a length of 2 here. Split on the `-`.

2017-11-07 17:17 UTC, armills commented on src/util/hass-translation.html
> +    if (language.substring(0, 2) === 'zh') {
We should spilt on the dash here as well, so we aren't matching three letter language codes that begin with `zh`.

2018-01-22 16:05 UTC, closed without merging