UI for climate state-card that support on/off
home-assistant/frontend pull request #784
Opened 2018-01-04 07:36 UTC by andrey-git

If climate device doesn't support on/off the UI stays like it was before.

If the device *does* support on/off then it will look like in the screenshot below.
Note that if state if "off" the bold part will show *current operation* (as "off" is evident from the toggle).
Otherwise the bold part will show state like it did before.
![climate](https://user-images.githubusercontent.com/5478779/34553818-3a58a93e-f132-11e7-8898-69ab0f95bdc0.png)

2018-01-04 19:30 UTC, MartinHjelmare commented
Can you add a screenshot of how it looks when the toggle is off?

2018-01-04 19:33 UTC, ciotlosm commented
Can it also have an icon color change like switches if it has on/off state?

2018-01-04 20:02 UTC, andrey-git commented
@MartinHjelmare 
Off looks exactly the same (except for the toggle). I added a screesnhot

@ciotlosm I agree that would be good, but lets keep this PR as simple as possible.

2018-01-05 08:00 UTC, balloob requested changes
I don't like this because it deviates from all other state cards in Home Assistant which are 40px high. That is either 2 rows of text or 1 interactive component.

2018-01-05 08:53 UTC, andrey-git commented
It could be made into a full card, but then some people like it compact and want a state-card for media_player too.

I tried put everything on the same 40px "line" but it doesn't fit well for narrow columns.

Another option is to drop the current operation completely and make climate use toggle-type state card, but then I feel it would show not enough info and I personally would resort to customUI to add data anyway.


How do you think the climate UI should look like?

2018-01-05 09:00 UTC, ciotlosm commented
@andrey-git Just a note: current operation is actually state (which happens to be current operation for most)

My suggestion would be: 

![screen shot 2018-01-05 at 11 02 41](https://user-images.githubusercontent.com/7738048/34602230-aceb183a-f207-11e7-8b3e-53e7d2e8489d.png)

2018-01-05 11:14 UTC, andrey-git commented
@ciotlosm I tried that - the colums could be as narrow as 300px and it won't fit

2018-01-06 07:08 UTC, andrey-git commented
@balloob 
Proposal that could benefit both climate and media_player:
introduce "inline-cards":

Those would be placed in groups like state-cards but would take 2 "lines" i.e. be 96px height (including outer padding).

media_player can use it to show info (1st line) and control buttons (2nd line)

ha-cards should be aware of this and count inline-cards as 2 spaces when selecting columns.

2018-01-06 22:44 UTC, balloob commented
I don't like the idea of inline cards because it makes the line height per row inconsistent. It also violates the material design guidelines.

What if it would just replace the bold text with "off" when it's off. Allow toggling on from the more info card ? There is currently only 1 climate integration that has an on/off toggle. It doesn't seem to make sense to make a lot of changes to accomodate 1 out of the 28 climate integrations.

2018-01-07 05:53 UTC, andrey-git commented
What do you mean, light height per row?

2018-01-07 07:25 UTC, balloob commented
![image](https://user-images.githubusercontent.com/1444314/34647482-d22a04d0-f338-11e7-9e35-0244e2a58307.png)

2018-01-07 09:20 UTC, andrey-git commented
The proposed inline-card would take *exactly* two lines, so it won't break the "grid"
(btw the current climate state-card is 2px too high)

2018-01-10 00:38 UTC, balloob commented
Toggles are 48x48

![image](https://user-images.githubusercontent.com/1444314/34750327-6517cf9c-f55b-11e7-8dc6-4d2cc3958497.png)

48x48 is the minimum touch target as set by the [material design guidelines](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size)

2018-03-04 07:57 UTC, closed without merging