Add button to call lock.open to lock state card
home-assistant/frontend pull request #8384
Opened 2021-02-12 23:55 UTC by kroimon

## Proposed change

This adds a new 'Open' button to the state card for the lock entity that calls the `lock.open` service.
The button is placed next to the 'Lock' and 'Unlock' buttons and is hidden if the lock does not support this feature.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: none
- This PR is related to issue or discussion: none
- Link to documentation pull request: none

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-02-14 16:56 UTC, spacegaier commented
Please add a screenshot in your description.

2021-02-24 16:20 UTC, bramkragten approved these changes

2021-02-24 16:23 UTC, bramkragten requested changes
And please add a screenshot :-)

2021-02-24 16:23 UTC, bramkragten commented on src/state-summary/state-card-lock.js
> +          hidden$="[[!canOpen]]"
Nothing is done with this attribute, so it will never be hidden.

2021-06-01 17:19 UTC, closed without merging