Fix display issues on old browsers
home-assistant/frontend pull request #901
Opened 2018-02-19 00:53 UTC by NovapaX

This fixes some (bad) display issues on older devices.
ShadyCSS now correctly polyfills the default colors set in ha-style.
Before it somehow did not 'find' the css variables in the defaults because they were set with the wrong selector.

**documentation reference**
https://www.polymer-project.org/2.0/docs/upgrade#update-custom-property-syntax
see the comment in the code snippet under "After (hybrid code)" which states:
` /* In a 2.x custom-style use the html selector to set global defaults */`

**Images before and after**
![img_0270](https://user-images.githubusercontent.com/411716/36359063-82b89aa0-1517-11e8-8d60-a40fc403e7f9.PNG)
![img_0271](https://user-images.githubusercontent.com/411716/36359066-8e0df3fa-1517-11e8-93b3-e52185a4dbb2.PNG)

2018-02-19 05:38 UTC, andrey-git requested changes
This needs another solution. Polymer have some default styles applied to html. When our styles are also applied to html it becomes order dependent. Thus I moved our styles to body.

2018-02-19 08:15 UTC, NovapaX commented
It's weird because this is obviously the way it 'should' be done.
I guess #354 is solving a symptom and not the problem.

Anyway.
- turning it into `html, body {` doesn't work.
- turning the whole block into a mixin and applying it to both html and body doesn't work either.

2018-02-19 10:44 UTC, andrey-git commented
Which browser is broken now? Safari9?

2018-02-19 10:46 UTC, NovapaX commented
Yes. It's safari on iOS 9.
But the issue is with shadowCSS polyfill not correctly using the css variables when generating the shadowy CSS style. 
So other old browsers are probably affected with the same issue.

2018-02-19 11:02 UTC, andrey-git commented
If you can reproduce it on some browser that works on Linux I can take back look.

2018-02-19 11:45 UTC, NovapaX commented
Chrome 48 exhibits the exact same behavior as iOS 9.3 safari. (that's the last chrome version that does not support css-variables)

note: The safari version at hand should support css-variables, but apparently shadyCSS is not able to determine that and 'compiles' the variables into values anyway.

2018-02-19 16:17 UTC, andrey-git commented
IIUC this is not about css variables, but about shadow DOM.

2018-02-19 17:50 UTC, andrey-git commented
Try the following style content: https://hastebin.com/bicicayotu.lua

I basically duplicated overridable content for both `html` and `body`

2018-02-19 18:09 UTC, NovapaX commented
Will try that. Of course that will work.
It’s about both shadow dom and CSS variables. When shadow dom is not supported but css-vars are, shadowCSS will polyfill css styles but keep the css-variable references intact.
Only when css variables are not supported it will also substitute those with the values.

2018-02-19 21:00 UTC, NovapaX commented
You code snippet worked (of course)
It may not be elegant, but it works. 
I was however not able to reproduce the issue with the styles being overridden. (at least not in with the config panels)

2018-02-26 01:06 UTC, NovapaX commented
Any changes still needed on this?

2018-02-26 11:21 UTC, NovapaX commented
I've been looking at this again, and I just really think https://github.com/home-assistant/home-assistant-polymer/pull/354 needs another solution.
Unfortunately I can't easily test the zwave panel, but all configuration panels (including iframes) behave properly with global styles set on `html`.
I think we should just change it back and solve the 'order' issues a different way.

2018-02-26 18:50 UTC, balloob commented
I think you just had the right solution in the chat. We need to import the paper styles here first so that we override them. Because it is just an ordering problem.

2018-02-26 18:56 UTC, NovapaX commented
Polymer styles are already correctly imported at the top of ha-styles.html by importing polymer.html 
There also is no ordering issue in the default home-assistant panels as far as I can see.
It was a problem with the zwave panel (which I unfortunately cannot test easily)
see: #340

2018-02-26 19:00 UTC, c727 commented on src/resources/ha-style.html
> +  To prevent overriding of thse styles by Polymer-defaults we define
the

2018-02-26 19:30 UTC, andrey-git commented
No, the problem a wasn't specific to zwave. I'll test again tomorrow.

2018-02-26 19:43 UTC, balloob commented
@NovapaX the styles are not imported as part of the polymer import. That's just the framework. We should explicitly import the HTML import that is messing with the styles. Guess it's `bower_components/paper-styles/paper-styles.html` ?

2018-02-26 20:39 UTC, balloob commented
@NovapaX did you test this and does this work?

2018-02-26 22:14 UTC, NovapaX commented
Yes, I tested this on both chrome 48 and iOS 9 (which both behaved the same).
And of course tested it on recent chrome and safari.

note: I tested it by doing `build_frontend`, installing it into hass with `pip` and commenting out the required front-end version in `frontend/init`. So it wouldn't be in dev-mode.

2018-02-27 00:16 UTC, merged

2018-10-10 20:19 UTC, ingoha commented
Should the frontend work with iOS 9.3.5 (hass version 0.79.3)? For me it does not :-/