Add navigation option from more-info to history
home-assistant/frontend pull request #9717
Opened 2021-08-05 07:14 UTC by spacegaier

## Breaking change

## Proposed change

Add easy navigation path from more-info to history for that specific entity.

![image](https://user-images.githubusercontent.com/114137/128307610-19fc611f-cca0-472f-9deb-d9ae6ab88712.png)

We need to align on the UX, see https://discord.com/channels/330944238910963714/867715211619074048/871052261739102228.

Additionally, we need to define how the history panel should accept input data. For this initial PR version I went with:

``/history/<entity_id>, for example /history/sensor.processor_temperature``

But perhaps there are better options to only provide the filter only via parameters, similar to what the config integration jump to device or entities does:
``/config/entities?historyBack=1&config_entry=a84cba1d63f264fde6df9d75203eb784``

So we could also go with this instead (the period parameter is just something we could add in the future):
``/history?entity_id=<entity_id>&period=last-week`` 

ToDo:
- [ ] Align UX with @matthiasdebaat 
- [ ] Align "API" of history panel with @bramkragten 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-08-05 08:12 UTC, bramkragten commented
Yeah, I think we should do the params in query parameters.

This makes it more flexible and future proof.

Besides, we don't go to a different page as the URL would indicate otherwise.

2021-08-05 08:13 UTC, bramkragten requested changes

2021-08-05 08:13 UTC, bramkragten commented on src/dialogs/more-info/ha-more-info-dialog.ts
> +              @click=${this._gotoHistory}
Don't use navigate but an `<a href="...">`

2021-08-05 19:49 UTC, matthiasdebaat commented
If tried different things that resulted in a cluttered dialog. I like your proposal the most. Let’s merge this 😎

2021-08-05 23:07 UTC, bramkragten commented
> If tried different things that resulted in a cluttered dialog. I like your proposal the most. Let’s merge this 😎

Be aware that in some cases there is an extra button there to go to the config, like automation, script, zones...

Having 3 buttons there is not nice I think

2021-08-05 23:10 UTC, bramkragten commented on src/dialogs/more-info/ha-more-info-dialog.ts
> +            <mwc-icon-button
We should check `_computeShowHistoryComponent` before showing this button.

2021-08-08 21:02 UTC, spacegaier commented
@matthiasdebaat How do we proceed?
@bramkragten Any alternative ideas where to put the navigation option instead?

2021-08-09 14:36 UTC, matthiasdebaat commented
> @matthiasdebaat How do we proceed?
> @bramkragten Any alternative ideas where to put the navigation option instead?

Been working on a mockup with a [prototype](https://www.figma.com/proto/qXKRj9RnoC1yBKBQw6ne8t/UX-Hitlist?page-id=112%3A7&node-id=119%3A155&viewport=2271%2C-308%2C0.5146418809890747&scaling=min-zoom&starting-point-node-id=119%3A155). You can find the current more-info dialog and a new proposal, including showing more history. It's now a small text link underneath every graph.

I started this design to make the dialog more consistent by:

- Moving the close button to the right instead of left.
- Showing all tabs, so the user can see all the options at once. Only thing I'm wondering if we should make the related tab this prominent?

@spacegaier what do you think of the small text link?

2021-08-11 06:32 UTC, spacegaier commented
@matthiasdebaat I think the position of the text link is confusing if we have a history and a logbook section. The fact that it is below the logbook (and therefore visually "tied" to it) but relates to the history is weird to me.

I think putting it in the green box position is more logical, even though probably less pleasing visually:
![image](https://user-images.githubusercontent.com/114137/128980431-405f5e82-ad1f-4804-bb98-4f3ddeb22485.png)

We could also discuss if having a link to the logbook panel might also be beneficial. That way we would have consistent options for both history and logbook.

2021-08-11 07:48 UTC, matthiasdebaat commented
> @matthiasdebaat I think the position of the text link is confusing if we have a history and a logbook section. The fact that it is below the logbook (and therefore visually "tied" to it) but relates to the history is weird to me.
> 
> I think putting it in the green box position is more logical, even though probably less pleasing visually:
> 
> We could also discuss if having a link to the logbook panel might also be beneficial. That way we would have consistent options for both history and logbook.

Great suggestion! That looks like this.
![More-info dialog history](https://user-images.githubusercontent.com/20203284/128990478-26a610cb-d5b5-490f-bb4b-f374b3d8ecb1.png)

2021-08-11 11:02 UTC, bramkragten commented
I proposed this a while back, might make it even more clear? <https://github.com/home-assistant/frontend/pull/8231#issuecomment-831112882>

2021-08-11 14:03 UTC, spacegaier commented
The idea from Bram is also nice since it could provide some more visual guidance for the dialog: Clear visual blocks / sections for history and logbook (if we put a bold font title with a horizontal line below it across the dialog width for each section).

In the end Bram's proposal would not require any more screen space than the one from Mathias since the "See more" links would be in the same line as the new section headers.

@matthiasdebaat What do you think of Bram's idea? Could you add that as a mockup to Figma? I never really worked with that tool plus I assume I don't have authorization to add that to your mockup there.

2021-08-20 11:26 UTC, spacegaier commented
>
> I like it ❤️
> Only thing I'm wondering is, should the tab still be name `History`?

Sorry, I had somehow missed your last response.

=> What would be alternative for the tab name? I currently cannot think of another, better word. Changing to "Log" or "Logbook" is probably not the best, since I think we have a history graph more often then we do have a logbook section.

"History" is also what most/all current browser use, so I think commonly users get the idea what it relates to.

2021-09-13 09:15 UTC, matthiasdebaat commented
> "History" is also what most/all current browser use, so I think commonly users get the idea what it relates to.

Yeah, lets keep it `History`

2021-10-26 19:12 UTC, bramkragten approved these changes

2021-10-26 19:12 UTC, merged