:bug: - Fix initial view options for Calendar Card
home-assistant/frontend pull request #9984
Opened 2021-09-07 14:05 UTC by drinfernoo

## Proposed change

This fixes the UI editor to offer the `list` option in the "Initial View" selector for the Calendar Card.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: calendar
entities:
  - calendar.family
  - calendar.money
initial_view: list
```

## Additional information

- This PR fixes or closes issue: fixes #9954
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/pull/7541
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-09-07 14:42 UTC, drinfernoo commented
I'm not exactly sure if there should be further changes... It does appear that using `listWeek` (as used to be supported) shows the week beginning with the preceding Sunday, but using `list` (as per the linked PR) starts the week on the current day.

This PR only fixes the UI editor to make the "List View" option align with the supported value from the card, so that the card displays from the current day when configured via the editor.

Should we attempt to support both options? This would likely mean a couple other changes to the card.

2021-09-08 17:27 UTC, spacegaier requested changes
You also need to adjust `en.json` since the translation key currently is "listWeek". With this change we will loose all existing translations for it.

The perhaps better alternative could be to keep "listWeek" and adjust the frontend coding to expect that value (since in the future there might also be a "listDay").

2021-09-08 17:47 UTC, drinfernoo commented
> You also need to adjust `en.json` since the translation key currently is "listWeek". With this change we will loose all existing translations for it.
> 
> The perhaps better alternative could be to keep "listWeek" and adjust the frontend coding to expect that value (since in the future there might also be a "listDay").

I've updated `en.json`... I'm not sure exactly what to do with the3 card to properly change it *back* to using `listWeek` and still maintain the proper (or at least current) behavior, as there already appears to be different behavior between using `list` and `listWeek`.

2021-09-08 19:19 UTC, spacegaier commented
I will create a proposal PR how it could look like

2021-09-09 13:45 UTC, closed without merging